@echo off
setlocal enabledelayedexpansion

echo ========================================
echo  Finance Platform - Global Installer
echo ========================================
echo.

:: Get current directory (where the project is)
set "PROJECT_DIR=%~dp0"
set "PROJECT_DIR=%PROJECT_DIR:~0,-1%"

:: Create launcher script in a global location
set "GLOBAL_LAUNCHER=%USERPROFILE%\finance-launcher.bat"

echo Creating global launcher at: %GLOBAL_LAUNCHER%
echo.

:: Create the global launcher script
(
echo @echo off
echo :: Global Finance Platform Launcher
echo :: Auto-generated by install-launcher.bat
echo.
echo set "PROJECT_ROOT=%PROJECT_DIR%"
echo.
echo if not exist "%%PROJECT_ROOT%%\launcher.bat" ^(
echo     echo Error: Finance platform not found at %%PROJECT_ROOT%%
echo     echo Please reinstall or check the project location.
echo     pause
echo     exit /b 1
echo ^)
echo.
echo echo Starting Finance Platform from: %%PROJECT_ROOT%%
echo cd /d "%%PROJECT_ROOT%%"
echo call launcher.bat
) > "%GLOBAL_LAUNCHER%"

if exist "%GLOBAL_LAUNCHER%" (
    echo ✓ Global launcher created successfully!
    echo.
    echo You can now run the Finance Platform from anywhere by typing:
    echo   %GLOBAL_LAUNCHER%
    echo.
    echo Or create a desktop shortcut to this file.
    echo.
) else (
    echo ✗ Failed to create global launcher!
    echo.
)

:: Optionally add to PATH (requires admin rights)
echo Would you like to add the launcher to your PATH? ^(Y/N^)
set /p "ADD_TO_PATH="

if /i "!ADD_TO_PATH!"=="Y" (
    echo.
    echo Adding to PATH requires administrator privileges...
    echo Please run this script as administrator if you want PATH integration.
    echo.
    echo Alternatively, you can manually add this folder to your PATH:
    echo %USERPROFILE%
    echo.
)

:: Create desktop shortcut
echo Would you like to create a desktop shortcut? ^(Y/N^)
set /p "CREATE_SHORTCUT="

if /i "!CREATE_SHORTCUT!"=="Y" (
    set "DESKTOP=%USERPROFILE%\Desktop"
    set "SHORTCUT_PATH=!DESKTOP!\Finance Platform.lnk"
    
    :: Create VBS script to create shortcut
    set "VBS_SCRIPT=%TEMP%\create_shortcut.vbs"
    (
        echo Set oWS = WScript.CreateObject^("WScript.Shell"^)
        echo sLinkFile = "!SHORTCUT_PATH!"
        echo Set oLink = oWS.CreateShortcut^(sLinkFile^)
        echo oLink.TargetPath = "%GLOBAL_LAUNCHER%"
        echo oLink.WorkingDirectory = "%PROJECT_DIR%"
        echo oLink.Description = "Personal Finance Management Platform"
        echo oLink.IconLocation = "shell32.dll,3"
        echo oLink.Save
    ) > "!VBS_SCRIPT!"
    
    cscript //nologo "!VBS_SCRIPT!"
    del "!VBS_SCRIPT!"
    
    if exist "!SHORTCUT_PATH!" (
        echo ✓ Desktop shortcut created successfully!
    ) else (
        echo ✗ Failed to create desktop shortcut.
    )
)

echo.
echo ========================================
echo  Installation Complete!
echo ========================================
echo.
echo Ways to start the Finance Platform:
echo.
echo 1. Double-click: %GLOBAL_LAUNCHER%
if exist "%USERPROFILE%\Desktop\Finance Platform.lnk" (
    echo 2. Double-click the desktop shortcut
)
echo 3. From command line: "%GLOBAL_LAUNCHER%"
echo 4. From project folder: launcher.bat
echo.
echo Press any key to exit...
pause > nul
